<?php
include_once Views . 'header.phtml';
?>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3" style="border: 1px solid black;min-height:400px;padding-top: 40px">
            <p style="text-transform: capitalize">
               Dear
                <?php
                    echo $this->viewData['firstName'] . ' ' . $this->viewData['lastName'];
                ?>
                ,<br><br>
                your application with the access code
                <?php
                echo $this->viewData['accessCode'];
                ?>
                 is successful.<br><br>
                kindly print application status and application details by clicking the buttons below
            </p>
            <div class="row" style="margin-top: 50px">
                <div class="col-xs-4 col-xs-offset-1">
                    <a href="/home/status"><input type="button" value="Application Status" style="width: 100%;height: 40px;background-color: lightpink;
                        color: black;
                    "></a>
                </div>
                <div class="col-xs-4 col-xs-offset-1">
                    <a href="/home/detail"><input type="button" value="Application Detail" style="width: 100%;height: 40px;background-color: lightpink;
                        color: black;
                    "></a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
include_once Views . 'footer.phtml';
?>
