<?php
include_once Views . 'header.phtml';
?>

<div class="container">
        <div class="row" style="border: 1px solid black">
            <div class="row" style="padding: 20px 0">
                <h2 class="col-md-8 col-md-offset-4 col-xs-10 col-xs-offset-2">APPLICANT'S DETAILS</h2>
            </div>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3">
                    <?php
                    echo '<img width="100%" height="260px" src="/images/'. $this->viewData['image'] .'"/>';
                    ?>
                </div>
            </div>
            <div style="padding: 20px 20px">
                <p style="text-transform: capitalize">
                    dear
                    <?php
                    echo $this->viewData['firstName'] . ' ' . $this->viewData['lastName'];
                    ?>
                    , your application details have been received.<br><br>
                    your access code is
                    <?php
                    echo $this->viewData['accessCode'];
                    ?>
                    . Kindly go through the details.
                </p>
            </div>

            <div style="padding: 0 20px">
                <table class="table table-bordered">
                    <?php
                    foreach ($this->viewData['tableRows'] as $rowName => $rowValue) {
                        if($rowName== 'Select Best Subject') {
                    ?>
                            <tr>
                                <td>
                                    <label for="<?php echo $rowName; ?>"><?php echo $rowName; ?></label>
                                </td>
                                <td style="text-transform: capitalize">
                                    <?php
                                    for($i= 0;$i < count($rowValue);$i++){
                                        if($i === (count($rowValue) - 1)){
                                            echo $rowValue[$i];
                                            continue;
                                        }
                                        echo $rowValue[$i]. '<br>';
                                    }

                                    ?>
                                </td>
                            </tr>
                     <?php
                            continue;
                        }
                     ?>
                        <tr>
                            <td>
                                <label for="<?php echo $rowName; ?>"><?php echo $rowName; ?></label>
                            </td>
                            <td style="text-transform: capitalize">
                                <?php
                                echo $rowValue;
                                ?>
                            </td>
                        </tr>
                    <?php
                    }
                    ?>
                </table>
            </div>
        </div>
</div>
<?php
include_once Views . 'footer.phtml';
?>
