<?php
include_once Views . 'header.phtml';
?>

<div class="container">
    <div class="row"></br></br>
        <div class="col-md-6 col-md-offset-3" style="box-shadow:-4px -4px 4px rgba(0,0,0,.4);min-height:400px;padding: 20px 40px 120PX 40px;background: linear-gradient(to bottom right, #bdc3c7, #2c3e50);">
            <div class="row">
                <h2 class="col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1" style="color:ghostwhite">
                    APPLICANT'S STATUS
                </h2>
            </div><br>

            <div class="row">
                <div class="col-xs-9 col-xs-offset-1 col-md-6 col-md-offset-3">
                    <?php
                    echo '<img width="100%" height="200px" src="/images/'. $this->viewData['image'] .'" style="border-radius:5px"/>';
                    //echo $this->viewData['image'];
                    //echo '<img width="200px" height="200px" src="data:image/jpeg;base64,'.base64_encode($this->viewData['image']).'"/>';
                    ?>
                </div>
            </div><br><br>

            <div>
                <p style="text-transform: capitalize;color:ghostwhite;line-height:1em">
                    I
                    <?php
                    echo $this->viewData['firstName'] . ' ' . $this->viewData['lastName'];
                    ?>
                    ,&nbsp;
                    applied with the application code
                    <?php
                    echo $this->viewData['accessCode'];
                    ?>
                     <br><br>
                    i live at
                    <?php
                    echo $this->viewData['address'];
                    ?>
                     and i was born on
                    <?php
                    echo $this->viewData['dateOfBirth'];
                    ?>
                    .<br><br>
                    my favourite subjects are
                    <?php
                    $subjects= $this->viewData['subjects'];
                    for($i= 0;$i < count($subjects);$i++){
                        if($i === (count($subjects) - 1)){
                            echo $subjects[$i];
                            continue;
                        }
                        echo $subjects[$i]. ', ';
                    }
                    ?>

                </p>
            </div>
        </div>
    </div>
</div>

<?php
include_once Views . 'footer.phtml';
?>
