<!Doctype html>
<html lang="en">
    <head>
        <title>PHP mini Application</title>
        <meta charset="UTF-8">
        <meta name="view-port" content="width=device-width, initial-scale=1.0, maximum-scale= 1, user-scalable= no">
        <!--<link href="/css/home.css" rel="stylesheet"/>-->
        <!--<link href="/css/apply.css" rel="stylesheet"/>-->
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
    </head>
    <body>

